# Resources: https://www.youtube.com/watch?v=6yJ4xHkuKNE
version: "3.7"
# Version of docker compose
services:
    mysql:
        container_name: mysql-compose
        image: mysql:latest
        environment: 
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=database_development
        ports:
            - 4444:3306
        networks:
            - network1
    be-simplewms:
        container_name: "be-simplewms"
        image: dickyfahlevi21/be-simplewms:1.0.0
        ports:
            - 5555:3000
        depends_on: 
            - mysql
        # command: bash -c "npx sequelize-cli db:migrate"
        # kalau diberi command seperti ini, jadi tidak run containernya
        networks: 
            - network1

networks: 
    network1:
        name: network1

# docker-compose up -d
# -d = jalan di background, tidak ada log